env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "prettier"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: "module"
  project: ["./tsconfig.json"]
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-unused-vars":
    [warn, { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }]
