
namespace Torappu
{
	public enum AbnormalFlag
	{
		STUNNED = 0,
		SP_RECOVER_STOPPED = 1,
		TARGET_FREE = 2,
		BLOCK_FREE = 3,
		HIDDEN = 4,
		INVINCIBLE = 5,
		UNDEADABLE = 6,
		HEAL_FREE = 7,
		UNBALANCE_IMMUNE = 8,
		INVISIBLE = 9,
		UNUSED_PLACEHOLDER_2 = 14,
		ALLY_TARGET_FREE = 0xF,
		UNUSED_PLACEHOLDER_1 = 10,
		DISARMED = 11,
		SILENCED = 12,
		UNMOVABLE = 13,
		FROZEN = 0x10,
		E_NUM = 17
	}
}
