
namespace Torappu
{
	public enum AttributeType
	{
		MAX_HP,
		ATK,
		DEF,
		MAGIC_RESISTANCE,
		COST,
		BLOCK_CNT,
		MOVE_SPEED,
		ATTACK_SPEED,
		BASE_ATTACK_TIME,
		RESERVED_0,
		RESERVED_1,
		RESERVED_2,
		RESERVED_3,
		HP_RECOVERY_PER_SEC,
		SP_RECOVERY_PER_SEC,
		ABILITY_RANGE_FORWARD_EXTEND,
		MAX_DEPLOY_COUNT,
		DEF_PENETRATE,
		MAGIC_RESIST_PENETRATE,
		HP_RECOVERY_PER_SEC_BY_MAX_HP_RATIO,
		TAUNT_LEVEL,
		RESPAWN_TIME,
		MAX_DECK_STACK_CNT,
		MASS_LEVEL,
		BASE_FORCE_LEVEL,
		DEF_PENETRATE_FIXED,
		ONE_MINUS_STATUS_RESISTANCE,
		E_NUM
	}
}
