
namespace Torappu
{
    public enum ItemType
    {
        NONE,
        CHAR,
        CARD_EXP,
        MATERIAL,
        GOLD,
        EXP_PLAYER,
        TKT_TRY,
        TKT_RECRUIT,
        TKT_INST_FIN,
        TKT_GACHA,
        ACTIVITY_COIN,
        DIAMOND,
        DIAMOND_SHD,
        HGG_SHD,
        LGG_SHD,
        FURN,
        AP_GAMEPLAY,
        AP_BASE,
        SOCIAL_PT,
        CHAR_SKIN,
        TKT_GACHA_10,
        TKT_GACHA_PRSV,
        AP_ITEM,
        AP_SUPPLY,
        RENAMING_CARD,
        ET_STAGE,
        ACTIVITY_ITEM,
        VOUCHER_PICK,
        VOUCHER_CGACHA,
        VOUCHER_MGACHA,
        CRS_SHOP_COIN,
        CRS_RUNE_COIN,
        LMTGS_COIN,
        EPGS_COIN,
        LIMITED_TKT_GACHA_10,
        LIMITED_FREE_GACHA
    }
}
